### ISSUE TITLE
Javascript errors or clicking on Insert icon does nothing

### ISSUE THREAD

**Issue by rchavik** [croogo/Ckeditor#6]
> I have clean version of Croogo 2.1.0.
> When I'm trying to insert image to page in CKEditor, after I click on 
> 'Image->Browse' a window with all the attachments is opening 
> (/admin/file_manager/attachments/browse?CKEditor=NodeBody&CKEditorFuncNum=1&langCode=pl), 
> but after I click on insert icon there is an error:
> 
> "onclick="Croogo.Wysiwyg.choose('20140925-colzor-art1-3.jpg');"
> Uncaught TypeError: undefined is not a function "
> 
> I tried the same thing on Croogo 1.5.8 and it 's working without any errors.
> What can be the problem?

Ref: http://thread.gmane.org/gmane.comp.cms.croogo/1045

Possibly introduced in 32e095e23d70f7fc7934b86929d5a6406e8e67b4
Easiest fix would be to revert it.
